Repository Seven730/PWA-Project, pull requests merged in 2020-04, with the labels that each got.

#34 Style updates everywhere
  package-lock.json
  package.json
  src/Components/NavigationBar.jsx
  src/Components/NavigationBarStyle.css
  src/Screens/Account/Account.jsx
  src/Screens/AddPicture/AddPicture.jsx
  src/Screens/AddPicture/ImageCardAdd.jsx
  src/Screens/Home/Home.jsx
  src/Screens/Home/HomeStyle.css
  src/Screens/ImageGallery/ImageCard.jsx
  src/Screens/ImageGallery/ImageGallery.jsx
  src/Screens/ImageGallery/ImageGalleryStyle.css
  src/Screens/Login/Forms/EmailLoginForm.jsx
  src/Screens/Login/Login.jsx
  src/Screens/MyPhotos/ImageCardUploaded.jsx
  src/Screens/MyPhotos/MyPhotos.jsx
  src/Screens/MyPhotos/MyPhotosStyle.css
  src/Screens/Register/Register.jsx
  src/Screens/Register/RegisterForm.jsx
  src/Screens/Register/RegisterStyle.css
Labels: development, enhancement

#61 Refined style and responsivness for most screens
  src/Screens/Home/ConditionalLoginOrRegister.jsx
  src/Screens/Home/Home.jsx
  src/Screens/Home/HomeStyle.css
  src/Screens/ImageGallery/ImageGalleryStyle.css
  src/Screens/Login/Forms/EmailLoginForm.jsx
  src/Screens/Login/Forms/GoogleLoginForm.jsx
  src/Screens/Login/Login.jsx
  src/Screens/Login/LoginStyle.css
  src/Screens/Register/Register.jsx
  src/Screens/Register/RegisterForm.jsx
  src/Screens/Register/RegisterStyle.css
Labels: development

#65 fixing myPhotos
  package.json
  src/Screens/ImageGallery/ImageGallery.jsx
  src/Screens/MyPhotos/ImageCardUploaded.jsx
  src/Screens/MyPhotos/MyPhotos.jsx
  src/Screens/MyPhotos/MyPhotosWrapper.jsx
Labels: development

#66 gallery optimization
  package.json
  src/Screens/ImageGallery/ImageCard.jsx
  src/Screens/ImageGallery/ImageGallery.jsx
Labels: enhancement

#62 Merge develop into master
  package-lock.json
  package.json
  public/Upload.png
  public/Upload2.png
  src/App.jsx
  src/Components/ConditionalError.jsx
  src/Components/NavigationBar.jsx
  src/Components/NavigationBarStyle.css
  src/Handlers/UserAuthenticationHandler.js
  src/Handlers/UserUpdateHandler.js
  src/Model/Providers.js
  src/Model/User.js
  src/Screens/Account/AccordionCard.jsx
  src/Screens/Account/Account.jsx
  src/Screens/Account/AccountStyle.css
  src/Screens/Account/UpdateForm.jsx
  src/Screens/AddPicture/AddPicture.jsx
  src/Screens/AddPicture/AddPictureStyle.css
  src/Screens/AddPicture/ImageCardAdd.jsx
  src/Screens/AddPicture/Upload.png
  src/Screens/AddPicture/Upload2.png
  src/Screens/Home/ConditionalLoginOrRegister.jsx
  src/Screens/Home/Home.jsx
  src/Screens/Home/HomeStyle.css
  src/Screens/ImageGallery/ImageCard.jsx
  src/Screens/ImageGallery/ImageGallery.jsx
  src/Screens/ImageGallery/ImageGalleryStyle.css
  src/Screens/ImageGallery/RenderWrapper.jsx
  src/Screens/Login/Forms/EmailLoginForm.jsx
  src/Screens/Login/Forms/FacebookLoginForm.jsx
  src/Screens/Login/Forms/GoogleLoginForm.jsx
  src/Screens/Login/Login.jsx
  src/Screens/Login/LoginStyle.css
  src/Screens/MyPhotos/ImageCardUploaded.jsx
  src/Screens/MyPhotos/MyPhotos.jsx
  src/Screens/MyPhotos/MyPhotosStyle.css
  src/Screens/Register/Register.jsx
  src/Screens/Register/RegisterForm.jsx
  src/Screens/Register/RegisterStyle.css
  src/index.css
  src/index.jsx
Labels: development
